name: CI Test

on: 
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest  # This ensures a GitHub-hosted environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Verify Ruby Installation
        run: ruby -v

      - name: Run Tests
        run: bundle exec rake test  # Modify this to match your test command
